output: menu.o yomu.o buffer.o stack.o main.o
	g++ -std=c++11 menu.o yomu.o buffer.o stack.o main.o -o output

menu.o: menu.cpp
	g++ -c -g -std=c++11 menu.cpp

yomu.o: yomu.cpp
	g++ -c -g -std=c++11 yomu.cpp

buffer.o: buffer.cpp
	g++ -c -g -std=c++11 buffer.cpp

stack.o: stack.cpp
	g++ -c -g -std=c++11 stack.cpp

main.o: main.cpp
	g++ -c -g -std=c++11 main.cpp
